baseurl = "/"
languageCode = "en-us"
title = "NIBSC Bioinformatics Documentation"
theme = "minimal"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
    
[[menu.icon]]
    name = "github"
    url = "https://github.com/nibsbioinformatics/core"
    weight = 1
[[menu.icon]]
    name = "twitter"
    url = "https://twitter.com/nibsc_mhra"
    weight = 2

[params]
    description = "Documentation of NIBSC pipelines"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

